export const enum ESCREEN {
  "HOME_SCREEN" = "listen Now",
  "MAIN_SCREEN" = "main",
  "SEARCH_SCREEN" = "search",
  "SETTING_SCREEN" = "setting",
  "LOGIN_SCREEN" = "login",
  "SIGNUP_SCREEN" = "signup",
  "PLAYTRACK_SCREEN" = "playtrack",
  "PLAYING_TRACK" = "playing",
  "LIBRARY_SCREEN" = "library",
  "BOTTOM_MAIN" = "BOTTOM_MAIN",
  "BOTTOM_SEARCH" = "BOTTOM_SEARCH",
  "BOTTOM_SETTING" = "BOTTOM_SETTING",
  "SONG_LIST_DETAIL" = "songDetailList",
}
